### ISSUE TITLE
Can't install package, using nextjs 

### ISSUE THREAD

**Issue by anonymous-coder** [gfazioli/react-toggle#18] opened 2019-09-05 22:22 UTC
**Describe the bug**

error node_modules/react-toggle-component: Command failed.
Exit code: 127
Command: tsc -p tsconfig.json
Arguments: 
Directory: node_modules/react-toggle-component

**To Reproduce**
nextjs (9)
typescript (3.6.2) installed/
yarn add react-toggle-component

**Comment by adrian-delgado** [comment] 2019-09-06 11:31
Duplicate of #14

**Comment by gfazioli** [comment] 2019-11-14 13:27
should be ok on `v3.0.6`

**Closed by gfazioli** 2019-11-14 13:27 UTC
